version: "3"
services:
    youtube-dl:
      image: marquisexb13/ytdlp-frontend
      build:
        context: https://github.com/marquisexb13/ytdlp-frontend.git 
        #https://github.com/marquisexb13/ytdlp-frontend/edit/main/docker-compose.yml
        dockerfile: ./Dockerfile
      container_name: ytdlp-frontend
    #  environment:
    #    - DOWNLOAD_RATE=500K
    #    - APPRISE_SERVICE=discord://webhook_id/webhook_token
      volumes:
        - /volume1/docker/ytdlp-frontend/downloads:/downloads
      ports:
        - 10012:10012  #/tcp # HTTP proxy
      restart: unless-stopped
